services:
  postgres:
    image: postgres:15
    container_name: recetin_postgres
    environment:
      POSTGRES_DB: recetin_db
      POSTGRES_USER: recetin_user
      POSTGRES_PASSWORD: recetin_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

